### ISSUE TITLE
Omniauth (Google auth 2) Request phase initiated

### ISSUE THREAD

**Issue by vinhngl** [netguru/people#72]
Hi guys,

Can you help me resolve this error? I can not Sign up with Google. This is my config:

```ruby
  google_client_id:       99479291876-XXXX.apps.googleusercontent.com
  google_secret:          D_5LcaTIINXXXXXXX
  google_domain:        google.com
```
And the screenshot for this error
![1__tmux__tmux_](https://cloud.githubusercontent.com/assets/1997137/6577634/fc496f4e-c771-11e4-9c12-7e1b30a953db.png)

**Comment by no17436** [comment]
Hi @vinhngl 
As `google_domain` use the domain your server is running on.
Ex. `localhost:3000`.
It should also be set up in google console as authorized redirect :)

HTH.
